const WINDOW_WIDTH_1280 = 1280;
const WINDOW_WIDTH_768 = 768;

const SHORT_MOVIE_DURATION = 40;

const INITIAL_CARDS_L_SIZE = 12;
const ADDING_CARDS_L_SIZE = 3;

const INITIAL_CARDS_M_SIZE = 8;
const ADDING_CARDS_M_SIZE = 2;

const INITIAL_CARDS_S_SIZE = 5;
const ADDING_CARDS_S_SIZE = 2;

export {
	WINDOW_WIDTH_1280,
	WINDOW_WIDTH_768,
	SHORT_MOVIE_DURATION,
	INITIAL_CARDS_L_SIZE,
	ADDING_CARDS_L_SIZE,
	INITIAL_CARDS_M_SIZE,
	ADDING_CARDS_M_SIZE,
	INITIAL_CARDS_S_SIZE,
	ADDING_CARDS_S_SIZE,
};
