const WINDOW_WIDTH_1280 = 1280;
const WINDOW_WIDTH_768 = 768;

const CARDS_WIDTH_LARGE_START = 12;
const CARDS_WIDTH_MEDIUM_START = 8;
const CARDS_WIDTH_SMALL_START = 5;

const CARDS_WIDTH_LARGE_ADD = 3;
const CARDS_WIDTH_MEDIUM_ADD = 2;
const CARDS_WIDTH_SMALL_ADD = 2;


const SHORT_MOVIE_DURATION = 40;

export {
	WINDOW_WIDTH_1280,
	WINDOW_WIDTH_768,
	CARDS_WIDTH_LARGE_START,
	CARDS_WIDTH_MEDIUM_START,
	CARDS_WIDTH_SMALL_START,
	CARDS_WIDTH_LARGE_ADD,
	CARDS_WIDTH_MEDIUM_ADD,
	CARDS_WIDTH_SMALL_ADD,
	SHORT_MOVIE_DURATION,
};
